language: go
sudo: false
go:
  - 1.6
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -v -coverprofile=queue.coverprofile ./queue
  - go test -v -coverprofile=sched.coverprofile ./jobqueue/scheduler
  - go test -v -coverprofile=jq.coverprofile ./jobqueue
  - go test -v -coverprofile=cloud.coverprofile ./cloud
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
