# The format of this file is YAML
#
# VRPipe will load its configuration settings from one or more files named
# .vrpipe_config[.production|.development].yml found in these directories, in
# order of precedence:
# 1) The current directory
# 2) Your home directory
# 3) The directory pointed to by the environment variable $VRPIPE_CONFIG_DIR
#
# .vrpipe_config.yml files are always read, and can be used to define settings
# common to both production and development deployments.
# .vrpipe_config.production.yml files are only read in a production context:
# either a --deployment production option has been passed to the vrpipe
# executable, or the environment variable $VRPIPE_DEPLOYMENT has been set to
# 'production'.
# A similar story applies for .vrpipe_config.development.yml files, which are
# used when things are set to 'development'.
# The default deployment is production.
#
# If a setting is found in none of the files read, then an environment variable
# is checked: VRPIPE_<setting name in caps>. Eg. to define the manager_port
# option you might do:
# export VRPIPE_MANAGER_PORT="11301"
#
# Note that all worker nodes need to be able to see your desired set of config
# files, so either define them in environment variables or put the config files
# on a disc that is mounted and shared across all your compute nodes.


# manager_port: What port should the vrpipe manager listen on?
# This defaults to "11301". Note, this is a string (quoted).
# NB: It is very important to have different settings for your production
# manager and your development manager. If you have multiple developers running
# tests, each individual person should have their own unique manager_port 
# specified in their personal ~/.vrpipe_config.development.yml file.
#
# Before being able to use vrpipe you must start the manager by running 'vrpipe
# manager'. It will start listening on the specified port on your local host.
# Your other invocations of 'vrpipe' also use this option to know what port to
# connect to, but they'll only succeed if you run them from the same host you
# started the manager on, or if you have set the manager_host option to the
# host you started the manager on.
# vrpipe commands that are spawned by the manager itself are given the real
# ip address of the host the manager is running on, so these commands do not
# need manager_host to be set.
# For multi-machine systems it is required that all hosts that could end up
# running a vrpipe command be able to do tcp communication with the host you
# launch the manager on.
manager_port: "11301"

# manager_host: What host was 'vrpipe manager' started on?
# This is optional and defaults to "localhost".
#
# This option determines where vrpipe commands (other than the manager command)
# try and connect to your vrpipe manager. You only need to set this if you plan
# on running vrpipe commands yourself on a host that is different to the one you
# you plan to start the vrpipe manager on.
# For more details, see the notes for the manager_port option above.
manager_host: "localhost"

# manager_dir: Where should the vrpipe manager store its working files?
# This defaults to a directory named .vrpipe in your home directory.
#
# The files stored in here are, by default, the manager's pid file and log file.
manager_dir: "~/.vrpipe"

# manager_pid_file: Where should vrpipe manager store its pid file?
# This defaults to a file named "pid" in manager_dir.
#
# You can set this to an absolute path to ignore manager_dir; for example if
# you have the root permissions to set things up, you may prefer to set this to
# /var/run/vrpipe/pid
manager_pid_file: "pid"

# manager_log_file: Where should vrpipe manager store its log file?
# This defaults to a file named "log" in manager_dir.
#
# You can set this to an absolute path to ignore manager_dir; for example if
# you have the root permissions to set things up, you may prefer to set this to
# /var/log/vrpipe/pid
manager_log_file: "log"

# manager_umask: What umask should be used when vrpipe manager creates files?
# This defaults to 007 (user+group read+writable, no access to others).
# Note, this is a number (no quotes).
#
# Here are examples of alternative umasks:
# 022 = world readable, user read+writable
# 002 = world readable, user+group read+writable
manager_umask: 007
